version: '3.1'
services:
  registrator:
    image: gliderlabs/registrator:vendor
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal=true -deregister=always -ip=127.0.0.1 -cleanup -tags=registrator consul:8500
    network_mode: host

  consul:
    image: consul:1.0.6
    restart: always
    ports:
      - 127.0.0.1:8500:8500
    # networks:
    #   proxy:

  traefik:
    image: traefik:1.6
    restart: always
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:80:80
    volumes:
      - $PWD/config/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   proxy:

  tracing:
    image: jaegertracing/all-in-one:1.3.0
    restart: always
    ports:
      - 127.0.0.1:5775:5775/udp
      - 127.0.0.1:6831:6831/udp
      - 127.0.0.1:6832:6832/udp
      - 127.0.0.1:5778:5778/tcp
      - 127.0.0.1:16686:16686
      - 127.0.0.1:14268:14268
      - 127.0.0.1:9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    environment:
      - SERVICE_IGNORE=true
    # networks:
    #   proxy:
  
  prometheus:
    image: prom/prometheus:v2.2.1
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090
    # networks:
    #   proxy:
  
  grafana:
    image: grafana/grafana:5.0.4
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - SERVICE_IGNORE=true
    # networks:
    #   proxy:

  linkerd:
    image: buoyantio/linkerd:1.3.6
    ports:
      - 127.0.0.1:9990:9990 # Admin
      - 127.0.0.1:4140:4140 # Ingress/Outgoing
      - 127.0.0.1:4141:4141 # Outgress/Incoming
    volumes:
      - $PWD/config/linkerd.yaml:/config.yaml
    command: /config.yaml
    # networks:
    #   proxy:
    depends_on:
      - namerd
    # network_mode: host
    # privileged: true
    # Health check: "path": "/admin/ping"

  namerd:
    image: buoyantio/namerd:1.3.6
    ports:
      - 127.0.0.1:9991:9991 # Admin
      - 127.0.0.1:4100:4100 # Thrift
      - 127.0.0.1:4180:4180 # HTTP
    volumes:
      - $PWD/config/namerd.yaml:/config.yaml
    command: /config.yaml
    # network_mode: host
    # privileged: true
    # networks:
    #   proxy:

  node:
    image: alextanhongpin/echo
    restart: always
    environment:
      - SERVICE_NAME=echo
      - SERVICE_REGION=ap-southeast-1
      - SERVICE_TAGS=traefik.enable=true,traefik.backend=echo,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:echo.consul.localhost,traefik.frontend.passHostHeader=true
      # ,traefik.backend.circuitbreaker.expression='NetworkErrorRatio() > 0.5',traefik.backend.maxconn.amount=10,traefik.backend.maxconn.extractorfunc=client.ip
    ports:
      - 127.0.0.1::8080
    # networks:
    #   proxy:

  

# Services: mathsvc, thissvc, etc
# Storage: mongo, postgres
# Telemetry: Jaeger, Prometheus
# Cache: Redis
# Logging: EFK stack
# Visualization: Kibana, Grafana
# Key-Value, Service Discovery: Registrator, Consul
# Security: Vault
# Load-Balancer: Traefik
networks:
  discovery:
  proxy:
