admin:
  ip: 0.0.0.0
  port: 9991

# storage:
#   kind: io.l5d.consul
#   host: consul
#   port: 8500
#   datacenter: dc1
#   pathPrefix: /namerd/dtabs
#   readConsistencyMode: stale
#   writeConsistencyMode: stale
#   backoff:
#     kind: jittered
#     minMs: 10
#     maxMs: 10000
storage:
  kind: io.l5d.inMemory
  namespaces:
    default: |
      /grpc => /host;
      /svc => /host/web;
    consul_ingress: |
      /svc => /#/io.l5d.consul_ingress/dc1;
      /host        => /srv;
      /http/1.1/*  => /host;
    consul_egress: |
      /svc => /#/io.l5d.consul_egress/dc1;
      /host        => /srv;
      /http/1.1/*  => /host;

namers:
- kind: io.l5d.consul
  prefix: /io.l5d.consul_ingress
  host: consul
  port: 8500
  includeTag: false
  # useHealthCheck: true
  # healthStatuses:
  #   - "passing"
  #   - "warning"
  setHost: true
  consistencyMode: stale
  failFast: true
  preferServiceAddress: true

- kind: io.l5d.consul
  prefix: /io.l5d.consul_egress
  host: consul
  port: 8500
  includeTag: false
  # useHealthCheck: true
  # healthStatuses:
  #   - "passing"
  #   - "warning"
  setHost: true
  consistencyMode: stale
  failFast: true
  preferServiceAddress: true

interfaces:
  # used by linkerds to receive updates
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100

  # used by `namerctl` to manage configuration
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180